### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useContext') during build with next-export-optimize-images

### ISSUE THREAD

**Issue by holykzm** [dc7290/next-export-optimize-images#825] opened 2024-04-04 08:50 UTC
Title: Build Error with `next-export-optimize-images` on Next.js 14.1.0

---

#### Environment
- Next.js version: 14.1.0
- Library causing issue: `next-export-optimize-images`
- Node.js version: _(not specified)_
- Package Manager: pnpm
- Operating System: _(not specified)_

#### Description
When attempting to build a Next.js project using the `pnpm build` command, which internally calls `next build && next-export-optimize-images`, the process fails. Initially, a warning about the optional configuration not being loaded for `next-export-optimize-images` is displayed. Then, a `TypeError` related to React's `useContext` occurs during the static generation step, causing the build to fail and exit with `ELIFECYCLE` error code 1.

#### Steps to Reproduce
1. Run `pnpm build` in the project directory.
2. Observe the error in the terminal output.

#### Expected Behavior
The build process should complete without errors, successfully optimizing images for export.

#### Actual Behavior
The build process fails with a `TypeError` related to `useContext`, during the generation of static pages.

#### Terminal Log
_(See attached error message snippet from terminal output.)_

#### Sandbox Link
A sandbox replicating the issue is available here: [CodeSandbox Environment](https://codesandbox.io/p/devbox/keen-hertz-jry89m?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clukvh62600073d5vh998uka3%2522%252C%2522sizes%2522%253A%255B19.764705882352942%252C80.23529411764706%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clukvh62600023d5vx5fkv2eo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clukvh62600043d5vwr9utp9h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clukvh62600063d5vizv7pkb6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clukvh62600023d5vx5fkv2eo%2522%253A%257B%2522id%2522%253A%2522clukvh62600023d5vx5fkv2eo%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clukvh62600063d5vizv7pkb6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clukvh62600053d5vbw0osqh9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clukvh62600063d5vizv7pkb6%2522%252C%2522activeTabId%2522%253A%2522clukvh62600053d5vbw0osqh9%2522%257D%252C%2522clukvh62600043d5vwr9utp9h%2522%253A%257B%2522id%2522%253A%2522clukvh62600043d5vwr9utp9h%2522%252C%2522activeTabId%2522%253A%2522clukvhc45004d3d5vf7qd60ir%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clukvh62600033d5vwc5oxm6j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clukvhc45004d3d5vf7qd60ir%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clukvhca9002xdjfmgvsjcwrd%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

#### Possible Solutions
- Verify compatibility of `next-export-optimize-images` with Next.js version 14.1.0.
- Check for any missing or incorrect configuration that may be causing the `useContext` error.
- Look for similar issues or updates in the library's GitHub issues section.

```package.json
{
  "name": "nextjs-app-router",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build && next-export-optimize-images",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.1.0",
    "next-export-optimize-images": "^3.3.0",
    "react": "^18",
    "react-dom": "^18",
    "sharp": "^0.33.3"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.1.0",
    "typescript": "^5"
  }
}

```
---

I'd appreciate any insights or solutions for this problem. Thank you for your assistance!

**Comment by brunorzn** [comment] 2024-04-07 10:42
Same error here, using Next 14.1.3

**Comment by stavros-k** [comment] 2024-04-09 06:33
Duplicate of https://github.com/dc7290/next-export-optimize-images/issues/696

**Comment by h0lme3** [comment] 2024-04-10 13:59
No update yet?

**Comment by dc7290** [comment] 2024-04-10 14:35
We will soon be able to issue a revised release.
We are preparing to do so, as it will contain some disruptive changes.

**Closed by dc7290** 2024-04-10 14:35 UTC

**Comment by h0lme3** [comment] 2024-04-10 14:44
Looking forward to the updated version!
