### ISSUE TITLE
getOptimizedImageProps not being exported

### ISSUE THREAD

**Issue by jac00000b** [dc7290/next-export-optimize-images#981] opened 2024-08-01 08:22 UTC
**Describe the bug**
`getOptimizedImageProps` isn't being exported by the package

**To Reproduce**
1. Try to `import { getOptimizedImageProps } from "next-export-optimize-images/image";`
2. Typescript throws `Module '"next-export-optimize-images/image"' has no exported member 'getOptimizedImageProps'.`

**Expected behavior**
Return `getOptimizedImageProps` function

**Additional context**
I was following https://next-export-optimize-images.vercel.app/docs/Features/get-props

**Comment by dc7290** [comment] 2024-10-03 06:24
Thanks for the report!
Can you provide a reproducible repository or a sample in CodeSandbox?

**Comment by CEM-Christian** [comment] 2024-10-24 00:00
I'm having the same issue and created a CodeSandbox here: [https://codesandbox.io/p/devbox/c3cf2g](https://codesandbox.io/p/devbox/c3cf2g)
It just uses the NextJS default template, and attempts to define a component 'ImageWithArtDirection'

**Comment by dc7290** [comment] 2024-11-12 07:11
Upon investigation, it was discovered that the library code does not include the d.ts file.
https://www.npmjs.com/package/next-export-optimize-images?activeTab=code

I am looking into the reason.

**Comment by CEM-Christian** [comment] 2024-12-03 03:59
I've updated to the latest version but it appears the issue is still present?

Updated codebox: https://codesandbox.io/p/devbox/vibrant-violet-km42sy

**Comment by dc7290** [comment] 2024-12-09 20:55
tsupのバグでまだ引き続き発生しているようですね。。。
もう一度修正してみます。

**Comment by dc7290** [comment] 2024-12-12 14:42
@CEM-Christian 
I've confirmed that it has been fixed in v4.6.1!

**Closed by dc7290** 2024-12-12 14:42 UTC
Labels: released, released-in-v4.5.2
