### ISSUE TITLE
Exits with errors if no <Image /> is present. 

### ISSUE THREAD

**Issue by spudunk** [dc7290/next-export-optimize-images#195] opened 2022-08-22 00:14 UTC
**Describe the bug**
next-export-optimize-images fails if no <Image /> is present

**To Reproduce**
1. run create-next-app
2. setup next-export-optimize-images according to documentation, including new export script
3. clear index page so it is blank, remove all images from the project
4. run "npm run export" or npx next-export-optimize-images
5. See error

**Expected behavior**
Should not break build process but successfully optimize 0 / 0 assets

**Desktop (please complete the following information):**
 - OS: macOS arm64
 - Browser: Chrome
 - Version: any

**Comment by dc7290** [comment] 2022-08-22 21:10
@spudunk
Thanks.

Surely that should work fine.
Could you please share the error message?

**Comment by dc7290** [comment] 2022-08-26 13:16
@spudunk 
From the errors I'm seeing, it looks like you're using an API route that can't be used with `next export`!
https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features
This library only allows image components to be used with `next export`, so API routes are out of scope...

**Comment by spudunk** [comment] 2022-08-26 16:32
That's weird. I've created a branch with an appended error.txt file. 
[optimize-image-bug](https://github.com/spudunk/fernwehoutfitters.com/tree/optimize-image-bug)
This branch should produce the error.

I ran it again after deleting the API folder and have the same issue. 
Also, before deleting the API folder I had successful builds when a few Images were used. I just commented out the components in index.js to disable all the images and reproduce the error.

**Comment by dc7290** [comment] 2022-08-26 16:35
@spudunk 

I see.
That is certainly weird.

Thanks for providing the repository.
I will take a look at it.

**Comment by spudunk** [comment] 2022-08-27 01:07
While working on another project, a new boilerplate, I didn't have the issue initially, but after adding a few components I got the error again. 
Here's the repo for that project, it's cleaner and maybe easier to debug: [static-boilerplate](https://github.com/spudunk/static-boilerplate)

I'm probably doing something dumb but I'd really appreciate your feedback.

**Comment by dc7290** [comment] 2022-08-27 11:23
@spudunk 

The cause of the error was found.
As it turns out, there was an omission in the processing of cases where the image component was not used.
The error will stop occurring when a PR is released to correct the problem.

Until then, please use
- Using the image component
- Remove `withExportImage` from next.config.js
Please take the following measures.

**Comment by dc7290** [comment] 2022-08-27 11:24
@spudunk 

There was nothing wrong with your code, sir!

**Closed** 2022-08-27 11:25 UTC
